### ISSUE TITLE
Add deployment guide

### ISSUE THREAD

**Issue by evilbros7** [dylannalex/udemypy#4]
Bro Can U Can Heroku Deployment Guide Steps in Readme

**Comment by dylannalex** [comment]
A Heroku deployment guide sounds reasonable. I will be working on a Deployment Guide and Contribution Guide the next weeks.

**Comment by Script-Kiddie-JKB** [comment]
Cool Thanks So much, waiting..... 😊

**Comment by evilbros7** [comment]
Cool Thanks So much , waiting....😊

**Comment by evilbros7** [comment]
When adding bro

**Comment by dylannalex** [comment]
> When adding bro

I'm working on it right now!

**Comment by dylannalex** [comment]
Check out `CONTRIBUTING.md` to see how to contribute with UdemyPy development (this file includes a _Heroku Deployment_ section).

**Comment by evilbros7** [comment]
![IMG_20220813_031117](https://user-images.githubusercontent.com/69081291/184448657-9042f8b3-a7eb-4ba6-998e-966a184f616a.jpg)

Can you tell bro which file to be add in Procfile to run

**Comment by dylannalex** [comment]
There's no need to add a Procfile. You first have to setup your database. You can do that with:
- `python -m udemypy.database.setup`

Once you do that, you can run udemypy functionalities:

- `python -m udemypy.find_courses`: finds free courses and saves them to the database
- `python -m udemypy.clean_database`: removes courses that are no longer free in database
- `python -m udemypy.send_courses`: sends courses to Telegram and Twitter

You can run this commands with Heroku CLI (ideally for testing) or set up a Heroku scheduler.

**NOTE:** you don't need to deploy udemypy in Heroku to use it, you can run all this commands in your computer if that's easier for you.

**Comment by dylannalex** [comment]
You can now find this explained at the [How UdemyPy works](https://github.com/dylannalex/udemypy/blob/main/CONTRIBUTING.md#how-udemypy-works) section on the Contributing guide.

**Comment by evilbros7** [comment]
![IMG_20220829_022909](https://user-images.githubusercontent.com/69081291/187094338-15b9fdc7-e7e6-4819-9fc3-5562f87ad607.jpg)


I followed all this step but can't see option to run dynos bro
